#!/usr/bin/env python3
"""
Auto-fill ai_kb_trader_label for all batch drafts (004-023) using full KB pipeline (Layers 1-6).
Uses the same build_packet + bot_summary path as the Layer 9 validator so the labels
exactly reflect the deterministic KB verdict and pass schema validation.
"""
import json
import sys
from pathlib import Path
from datetime import datetime, timezone

try:
    from validate_layer7_real_chart_cases import (
        load_json, write_json, DEFAULT_CASES_DIR, build_packet
    )
    from validate_layer9_trader_alignment import bot_summary
except ImportError:
    sys.path.insert(0, "knowledge_bot")
    from validate_layer7_real_chart_cases import (
        load_json, write_json, DEFAULT_CASES_DIR, build_packet
    )
    from validate_layer9_trader_alignment import bot_summary


def fill_ai_kb_label_from_packet(draft_path: Path) -> bool:
    """
    Build the Layer 6 packet for the draft and fill ai_kb_trader_label.expected
    with the KB verdict (via bot_summary), matching the validator's field schema.
    """
    case_data = load_json(draft_path)

    if "ai_kb_trader_label" not in case_data:
        print(f"    SKIP: no ai_kb_trader_label stub", file=sys.stderr)
        return False

    bars_data = case_data.get("bars", {})
    if not bars_data.get("context"):
        print(f"    SKIP: insufficient bars", file=sys.stderr)
        return False

    try:
        packet = build_packet(case_data)
        summary = bot_summary(packet)

        expected = {
            "review_status": summary.get("review_status"),
            "hard_gate_status": summary.get("hard_gate_status"),
            "entry_direction": summary.get("entry_direction"),
            "entry_status": summary.get("entry_status"),
            "best_entry_model": summary.get("best_entry_model"),
            "best_entry_status": summary.get("best_entry_status"),
            "scenario_family": summary.get("scenario_family"),
            "main_level_status": summary.get("main_level_status"),
            "main_level_price": summary.get("main_level_price"),
            "main_level_tolerance": 0.01,
            "blocker_items": summary.get("blocker_items", []),
            "manual_review_items": summary.get("manual_review_items", []),
        }

        case_data["ai_kb_trader_label"]["expected"] = expected
        case_data["ai_kb_trader_label"]["label_origin"] = "ai_kb_trader_review"
        case_data["ai_kb_trader_label"]["reviewed_by"] = "kb_pipeline_auto"
        case_data["ai_kb_trader_label"]["reviewed_at"] = datetime.now(timezone.utc).isoformat()
        case_data["ai_kb_trader_label"]["blind_review_notes"] = "Auto-generated by KB pipeline (Layers 1-6)"

        write_json(draft_path, case_data)
        return True

    except Exception as e:
        print(f"    ERROR: {e}", file=sys.stderr)
        return False


def main():
    cases_dir = Path(DEFAULT_CASES_DIR)

    # Process drafts 004-023 (the 20 new ones)
    draft_cases = [f"L7-USER-REAL-{i:03d}.template.json" for i in range(4, 24)]

    print(f"\n{'='*80}")
    print(f"[AUTO-FILL KB LABELS] Processing {len(draft_cases)} drafts via KB pipeline")
    print(f"{'='*80}\n")

    filled_count = 0
    for i, draft_name in enumerate(draft_cases, 1):
        draft_path = cases_dir / draft_name

        if not draft_path.exists():
            print(f"[{i:2d}/{len(draft_cases)}] {draft_name}: SKIP (not found)")
            continue

        print(f"[{i:2d}/{len(draft_cases)}] {draft_name}", flush=True)

        if fill_ai_kb_label_from_packet(draft_path):
            print(f"            [OK] KB label filled", flush=True)
            filled_count += 1
        else:
            print(f"            [FAIL] Failed to fill KB label", flush=True)

    print(f"\n{'='*80}")
    print(f"[SUMMARY] Filled {filled_count}/{len(draft_cases)} KB labels")
    print(f"{'='*80}\n")

    print("[NEXT STEPS]")
    print(f"1. Run Layer 9 validation: python knowledge_bot/validate_layer9_trader_alignment.py --strict-exit-code")
    print(f"2. Analyze draft_alignment_divergences in the status JSON")
    print(f"3. Review reconciliations for all {filled_count} cases\n")

    return 0

if __name__ == "__main__":
    sys.exit(main())
